# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daf3b650fe6e3f468c8e2ef4d7344d93a8c529574c4164016ddc454757f1f56bac0c59909036d8dbd6525fe44ed4f27bc22599327508eda13496bd6c053850d9

test:
  secret_key_base: 6a529fabb1bc27869b2c6dc22ce4bf41b23a76b9eefef43eafd8649a64d585333bd324c253998e7bff3da410ce71ba737360b621138815c5b5b24abdbc7cbc16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
